config:
  # debug
  debug: false

  prompt:
    #Should the text sent in the chat be displayed?
    localEcho: false
    #Time limit before leaving the conversation.
    timeout: 180

  #The message will be shortened when loading gradients.
  minimize-on-loading: false
  #Check if updates are available, you will be notified when you log in to the server.
  update-checker: true
  #Time in milliseconds before clicking on the inventory again.
  clickCountdown: 500

  # List of worlds where players glow will be disabled
  glow:
    #Disable the glow of the player who enters the server if he does not have the permissions.
    check-glow-permission: true
    #Disable the player's glow if that glow no longer exists in menus.yml.
    check-glow-exist: true
    #It will deactivate and reactivate the glow if it receives invisibility effects.
    check-invisibility: true
    #Disables the glow if it is in gamemode SPECTATOR
    check-gamemode: true
    #Disables the glow when the player is sitting spinning and more.
    check-gsit: true
    #Disable the glow in the configured worlds.
    check-disguise: true
    disabled-worlds:
      - "Example"
      - "DisabledGlowWorld"

    auto-glow-on-join:
      enabled: false # Enables or disables the automatic glow feature when joining the server.
      override-existing: false # If true, replaces the player's current glow with a new one if they have the required permission.
      # If false, no changes will be applied if the player already has an active glow.

      # List of group-based configurations, defined by permissions.
      groups:
        vip:
          permission: "rank.vip" # Permission required to automatically apply this glow.
          glow: "gold"            # Name of the glow to be applied (must match one defined in the plugin's menus).
          priority: 100           # Group priority. If a player has multiple permissions, the glow from the group with the highest priority is applied.

        elite:
          permission: "rank.elite"
          glow: "aqua"
          priority: 80
        legend:
          permission: "rank.legend"
          glow: "rainbow"
          priority: 70



  #In this section you can add aliases or modify the base command of your choice.
  command:
    default:
      # Enable or disable the base command, this requires a server restart.
      enabled: true
      #Base command name, requires a server restart
      name: theglow
      #Aliases for the command
      aliases:
        - "jglow"

    # Base command for users
    shortened-open-command:
      # Disable the command here
      enabled: true
      # If this is true, users will need the permission assigned in permission to use the command.
      need-permissions: true
      permission: glow.open
      name: glow
      aliases:
        - "gw"

  # Change storage type from sqlite to mysql
  storage-method: SQLite

  data:
    address: 127.0.0.1
    port: 3306
    database: database
    username: username
    password: passy

file-version: '3'